matrix_host: "https://matrix.workhardpgh.com"
matrix_username: ""
matrix_password: ""
matrix_room: ""
spot_username: ""
spot_client_id: ""
spot_client_secret: ""
spot_playlist_id: ""
spot_redirect_uri: "http://localhost/"
